
-- ----------------------------------------------------------------------------------------------------------------
-- Generated by LLBLGen Pro v5.0  Build: 5.0.8
-- SQL Server 2000-2016/Express DDL Script generated from project: KSI
-- Project filename: C:\Users\Doolotbek\Desktop\KSI\CIS510\PowerKSI\KSI.llblgenproj
-- Script generated on: 26-Nov-2016 22:47.02
--
-- This is a Create script for creating a NEW data model. If you want DDL SQL for updating an existing model,
-- please create an Update script instead. 
--
-- This script might create schemas, which requires you to assign a proper user to the schema. Adjust the CREATE SCHEMA
-- statements below, if any, to avoid errors at runtime. Schemas aren't dropped in the DROP section.
--
--      >>>>> WARNING <<<<<
--      This is a CREATE script, with DROP statements for the existing tables, foreign keys and other constraints
--      This means that existing tables, data, constraints and other elements in the catalog/schemas addressed
--      are deleted. Use this Create script only to create new schemas with tables/constraints and other elements.
--
-- ----------------------------------------------------------------------------------------------------------------
-- ###############################################################################################################
-- DROP statements for existing elements. 
-- ###############################################################################################################
-- DROP statements for dropping existing elements with the same names as the ones created are commented out below. 
-- If you want to enable these statements for DROPping the existing elements first (which will remove all the data
-- in these existing elements), uncomment these statements by removing the two comment markers /* and */

-- Remove the comment marker on the NEXT line to enable DROP statements to remove existing elements
/* 

USE [KSI]
GO
-- ----------------------------------------------------------------------------------------------------------------
-- DROP Foreign keys
-- ----------------------------------------------------------------------------------------------------------------

ALTER TABLE [dbo].[ClassRegistration] DROP CONSTRAINT [FK_ClassRegistration_Offering]
GO

ALTER TABLE [dbo].[ClassRegistration] DROP CONSTRAINT [FK_ClassRegistration_Student]
GO

ALTER TABLE [dbo].[GradeBook] DROP CONSTRAINT [FK_GradeBook_GradeItem]
GO

ALTER TABLE [dbo].[GradeBook] DROP CONSTRAINT [FK_GradeBook_Offering]
GO

ALTER TABLE [dbo].[GradeBook] DROP CONSTRAINT [FK_GradeBook_Student]
GO

ALTER TABLE [dbo].[GradeBook] DROP CONSTRAINT [FK_GradeBook_User]
GO

ALTER TABLE [dbo].[Offering] DROP CONSTRAINT [FK_Offering_Course]
GO

ALTER TABLE [dbo].[Offering] DROP CONSTRAINT [FK_Offering_Instructor]
GO

ALTER TABLE [dbo].[Offering] DROP CONSTRAINT [FK_Offering_Instructor1]
GO

ALTER TABLE [dbo].[Offering] DROP CONSTRAINT [FK_Offering_Semester]
GO

ALTER TABLE [dbo].[OfferingSchedule] DROP CONSTRAINT [FK_OfferingSchedule_OfferingSchedule]
GO
-- ----------------------------------------------------------------------------------------------------------------
-- DROP tables for schema 'dbo' 
-- ----------------------------------------------------------------------------------------------------------------

DROP TABLE [dbo].[Attendance]
GO

DROP TABLE [dbo].[AttendanceCode]
GO

DROP TABLE [dbo].[ClassRegistration]
GO

DROP TABLE [dbo].[Course]
GO

DROP TABLE [dbo].[GradeBook]
GO

DROP TABLE [dbo].[GradeItem]
GO

DROP TABLE [dbo].[Offering]
GO

DROP TABLE [dbo].[OfferingSchedule]
GO

DROP TABLE [dbo].[Semester]
GO

DROP TABLE [dbo].[Student]
GO

DROP TABLE [dbo].[User]
GO
*/
-- Remove the comment marker on the PREVIOUS line to enable DROP statements to remove existing elements

-- ###############################################################################################################
-- Create statements for catalogs, schemas, tables and sequences
-- ###############################################################################################################
-- ----------------------------------------------------------------------------------------------------------------
-- Catalog 'KSI'
-- ----------------------------------------------------------------------------------------------------------------

USE master
GO
CREATE DATABASE [KSI] /* ON PRIMARY (NAME=KSI_dat, FILENAME='c:\mycatalogs\KSI.mdf', SIZE=10MB) */
GO


USE [KSI]
GO
-- ----------------------------------------------------------------------------------------------------------------
-- Schema 'dbo'
-- ----------------------------------------------------------------------------------------------------------------

-- -------[ Tables ]-----------------------------------------------------------------------------------------------

CREATE TABLE [dbo].[Attendance] 
(
	[DateOfAttendance] [date] NOT NULL, 
	[StudentId] [int] NOT NULL, 
	[OfferingId] [int] NOT NULL, 
	[AttendanceCodeId] [int] NOT NULL, 
	[SubmitDate] [datetime] NOT NULL, 
	[SubmittedBy] [int] NOT NULL, 
	[Notes] [varchar] (MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL 
)
GO

CREATE TABLE [dbo].[AttendanceCode] 
(
	[Id] [int] IDENTITY (1,1) NOT NULL, 
	[Name] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Type] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Status] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL 
)
GO

CREATE TABLE [dbo].[ClassRegistration] 
(
	[Id] [int] IDENTITY (1,1) NOT NULL, 
	[OfferingId] [int] NOT NULL, 
	[StudentId] [int] NOT NULL, 
	[IsOnline] [bit] NOT NULL, 
	[RegistrationDate] [datetime] NOT NULL, 
	[FinalGrade] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL 
)
GO

CREATE TABLE [dbo].[Course] 
(
	[Id] [int] IDENTITY (1,1) NOT NULL, 
	[CourseNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Title] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Description] [varchar] (MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[HasPrerequisite] [bit] NOT NULL, 
	[Syllabus] [varbinary] (MAX) NULL, 
	[Prerequisite1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
	[Prerequisite2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
	[Prerequisite3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL 
)
GO

CREATE TABLE [dbo].[GradeBook] 
(
	[Id] [int] IDENTITY (1,1) NOT NULL, 
	[OfferingId] [int] NOT NULL, 
	[StudentId] [int] NOT NULL, 
	[GradeItemId] [int] NOT NULL, 
	[Score] [int] NOT NULL, 
	[SubmitDate] [datetime] NOT NULL, 
	[SubmittedBy] [int] NOT NULL 
)
GO

CREATE TABLE [dbo].[GradeItem] 
(
	[Id] [int] IDENTITY (1,1) NOT NULL, 
	[Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Type] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[FullScore] [int] NOT NULL, 
	[Weight] [int] NOT NULL 
)
GO

CREATE TABLE [dbo].[Offering] 
(
	[Id] [int] IDENTITY (1,1) NOT NULL, 
	[SemesterId] [int] NOT NULL, 
	[CourseId] [int] NOT NULL, 
	[InstructorId] [int] NOT NULL, 
	[Instructor2Id] [int] NULL, 
	[Capacity] [int] NOT NULL, 
	[RoomNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL 
)
GO

CREATE TABLE [dbo].[OfferingSchedule] 
(
	[Id] [int] IDENTITY (1,1) NOT NULL, 
	[OfferingId] [int] NOT NULL, 
	[Weekday] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[StartTime] [time] NOT NULL, 
	[EndTime] [time] NOT NULL 
)
GO

CREATE TABLE [dbo].[Semester] 
(
	[Id] [int] IDENTITY (1,1) NOT NULL, 
	[Name] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[StartDate] [date] NOT NULL, 
	[EndDate] [date] NOT NULL 
)
GO

CREATE TABLE [dbo].[Student] 
(
	[Id] [int] IDENTITY (1,1) NOT NULL, 
	[StudentId] [int] NOT NULL, 
	[FirstName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[LastName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Email] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Status] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[IsOnline] [bit] NOT NULL 
)
GO

CREATE TABLE [dbo].[User] 
(
	[Id] [int] IDENTITY (1,1) NOT NULL, 
	[FirstName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[LastName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[FullName] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Email] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Username] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Password] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[LastLoginDate] [datetime] NULL, 
	[RefId] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[IsAdmin] [bit] NOT NULL 
)
GO

-- ###############################################################################################################
-- Create statements for Primary key constraints, Foreign key constraints, Unique constraints and Default Values
-- ###############################################################################################################
-- ----------------------------------------------------------------------------------------------------------------
-- Catalog 'KSI'
-- ----------------------------------------------------------------------------------------------------------------

USE [KSI]
GO
-- ----------------------------------------------------------------------------------------------------------------
-- Primary Key constraints for schema 'dbo'
-- ----------------------------------------------------------------------------------------------------------------

ALTER TABLE [dbo].[Attendance] WITH NOCHECK 
	ADD CONSTRAINT [PK_Attendance] PRIMARY KEY CLUSTERED 
	( 
		[DateOfAttendance], [StudentId], [OfferingId] 
	)
GO

ALTER TABLE [dbo].[AttendanceCode] WITH NOCHECK 
	ADD CONSTRAINT [PK_AttendanceCode] PRIMARY KEY CLUSTERED 
	( 
		[Id] 
	)
GO

ALTER TABLE [dbo].[ClassRegistration] WITH NOCHECK 
	ADD CONSTRAINT [PK_ClassRegistration] PRIMARY KEY CLUSTERED 
	( 
		[Id] 
	)
GO

ALTER TABLE [dbo].[Course] WITH NOCHECK 
	ADD CONSTRAINT [PK_Course] PRIMARY KEY CLUSTERED 
	( 
		[Id] 
	)
GO

ALTER TABLE [dbo].[GradeBook] WITH NOCHECK 
	ADD CONSTRAINT [PK_GradeBook] PRIMARY KEY CLUSTERED 
	( 
		[Id] 
	)
GO

ALTER TABLE [dbo].[GradeItem] WITH NOCHECK 
	ADD CONSTRAINT [PK_GradeItem] PRIMARY KEY CLUSTERED 
	( 
		[Id] 
	)
GO

ALTER TABLE [dbo].[Offering] WITH NOCHECK 
	ADD CONSTRAINT [PK_Offering] PRIMARY KEY CLUSTERED 
	( 
		[Id] 
	)
GO

ALTER TABLE [dbo].[OfferingSchedule] WITH NOCHECK 
	ADD CONSTRAINT [PK_OfferingSchedule] PRIMARY KEY CLUSTERED 
	( 
		[Id] 
	)
GO

ALTER TABLE [dbo].[Semester] WITH NOCHECK 
	ADD CONSTRAINT [PK_Semester] PRIMARY KEY CLUSTERED 
	( 
		[Id] 
	)
GO

ALTER TABLE [dbo].[Student] WITH NOCHECK 
	ADD CONSTRAINT [PK_Student] PRIMARY KEY CLUSTERED 
	( 
		[Id] 
	)
GO

ALTER TABLE [dbo].[User] WITH NOCHECK 
	ADD CONSTRAINT [PK_Instructor] PRIMARY KEY CLUSTERED 
	( 
		[Id] 
	)
GO
-- ----------------------------------------------------------------------------------------------------------------
-- Unique constraints for schema 'dbo'
-- ----------------------------------------------------------------------------------------------------------------
-- ----------------------------------------------------------------------------------------------------------------
-- Default values for schema 'dbo'
-- ----------------------------------------------------------------------------------------------------------------
-- ----------------------------------------------------------------------------------------------------------------
-- All foreign Key constraints
-- ----------------------------------------------------------------------------------------------------------------

ALTER TABLE [dbo].[ClassRegistration] 
	ADD CONSTRAINT [FK_ClassRegistration_Offering] FOREIGN KEY
	(
		[OfferingId] 
	)
	REFERENCES [dbo].[Offering]
	(
		[Id] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[ClassRegistration] 
	ADD CONSTRAINT [FK_ClassRegistration_Student] FOREIGN KEY
	(
		[StudentId] 
	)
	REFERENCES [dbo].[Student]
	(
		[Id] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[GradeBook] 
	ADD CONSTRAINT [FK_GradeBook_GradeItem] FOREIGN KEY
	(
		[GradeItemId] 
	)
	REFERENCES [dbo].[GradeItem]
	(
		[Id] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[GradeBook] 
	ADD CONSTRAINT [FK_GradeBook_Offering] FOREIGN KEY
	(
		[OfferingId] 
	)
	REFERENCES [dbo].[Offering]
	(
		[Id] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[GradeBook] 
	ADD CONSTRAINT [FK_GradeBook_Student] FOREIGN KEY
	(
		[StudentId] 
	)
	REFERENCES [dbo].[Student]
	(
		[Id] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[GradeBook] 
	ADD CONSTRAINT [FK_GradeBook_User] FOREIGN KEY
	(
		[SubmittedBy] 
	)
	REFERENCES [dbo].[User]
	(
		[Id] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[Offering] 
	ADD CONSTRAINT [FK_Offering_Course] FOREIGN KEY
	(
		[CourseId] 
	)
	REFERENCES [dbo].[Course]
	(
		[Id] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[Offering] 
	ADD CONSTRAINT [FK_Offering_Instructor] FOREIGN KEY
	(
		[InstructorId] 
	)
	REFERENCES [dbo].[User]
	(
		[Id] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[Offering] 
	ADD CONSTRAINT [FK_Offering_Instructor1] FOREIGN KEY
	(
		[Instructor2Id] 
	)
	REFERENCES [dbo].[User]
	(
		[Id] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[Offering] 
	ADD CONSTRAINT [FK_Offering_Semester] FOREIGN KEY
	(
		[SemesterId] 
	)
	REFERENCES [dbo].[Semester]
	(
		[Id] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[OfferingSchedule] 
	ADD CONSTRAINT [FK_OfferingSchedule_OfferingSchedule] FOREIGN KEY
	(
		[OfferingId] 
	)
	REFERENCES [dbo].[Offering]
	(
		[Id] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO

